# bilive Settings
[model]
model_type = "append" # Can be pipeline, append, merge

# WARNING!: If you choose "deploy" local inference:
# 1. Please check the VRAM requirements twice!
# 2. Please make sure you have installed the Nvidia GPU driver and can check the cuda via `nvcc -V`!
# WARNING!: If you choose "api":
# due to the limitation of free tier, you should keep every video less than 30 minutes(around)
# which means your MODEL_TYPE should not be "merge".
[video]
# You can change the title as you like, eg.
title = "{artist}直播-{date}" # Key words: {artist}, {date}, {title}, {source_link}
description = "." # Key words: {artist}, {date}, {title}, {source_link}
tid = 65 # The tid of the video(int), see https://bilitool.timerring.com/tid.html
gift_price_filter = 1 # The gift whose price is less than this value will be filtered, unit: RMB
reserve_for_fixing = false # If encounter MOOV crash error, delete the video or reserve for fixing
upload_line = "auto"
[download]
danmaku = false
