# bilive Settings
[model]
model_type = "append" # Can be append, or merge

[video]
# You can change the title as you like, eg.
title = "{artist}直播-{date}" # Key words: {artist}, {date}, {title}, {source_link}
description = "1" # Key words: {artist}, {date}, {title}, {source_link}
tid = 65 # The tid of the video(int), see https://bilitool.timerring.com/tid.html
reserve_for_fixing = false # If encounter MOOV crash error, delete the video or reserve for fixing
upload_line = "auto" # The upload line to be used, default None is auto detect(recommended), if you want to specify, it can be "bldsa", "ws", "tx", "qn", "bda2".
